name: 'demand_forecast'
version: '1.0.0'
require-dbt-version: ">=1.4.0"
config-version: 2

profile: 'demand_forecast'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
    demand_forecast:
        materialized: view
